name: "Patch Compatibility"

on:
  push:
    branches: [master, ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
jobs:
  analyse:
    name: Analyse
    runs-on: ubuntu-latest
    steps:
    - name: Checkout notqmail-patch
      run: git clone https://github.com/josuah/notqmail-patch/
    - name: Test whether we broke more patches than master did
      run: make -C notqmail-patch BRANCH=${{ github.sha }} brokemaster
